management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  metrics:
    export:
      prometheus:
        enabled: true
