spring:
  profiles:
    active: dev
  sleuth:
    propagation-keys:
      - X-Correlation-ID

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/d38f25aa-eab8-4c50-9f28-ebf92c1256f2/v2.0/
          jwk-set-uri: https://login.microsoftonline.com/navtestb2c.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1a_idporten_ver1

nav.no:
  cors-addresses:
  security:
    login-service-client-id: 0090b6e1-ffcc-4c37-bc21-049f7d1f0fe5

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  metrics:
    export:
      prometheus:
        enabled: true

