spring:
  profiles:
    active: q
  redis:
    host: ${REDIS_HOST}
    port: 6379

nav.no:
  security:
    cors:
      apply-to-path-pattern: '/**'
      allowed-origins:
        - 'https://omsorgspengesoknad-q.nav.no'
        - 'https://omsorgspengesoknad-api-q.nav.no'
        - 'https://omsorgspengesoknad.nais.oera-q.local'
      allowed-methods:
        - '*'
      max-age: 3600

storage:
  redis_mocked: false
  passphrase: ${STORAGE_PASSPHRASE}
