nav.no:
  authorization:
    api-gw-header: x-nav-apiKey
    api-gw-key: mock-key
  gateways:
    k9_lookup_url: 'http://localhost:8080/child-lookup'
  cors-addresses: 'http://localhost:**'

no-proxy: localhost,127.0.0.1,login.microsoftonline.com
http:
  proxyHost: localhost
  proxyPort: 8080
https:
  proxyHost: localhost
  proxyPort: 8080
