nav.no:
  security:
    login-service-client-id: 0090b6e1-ffcc-4c37-bc21-049f7d1f0fe5
    cors:
      apply-to-path-pattern: '/**'
      allowed-origins:
        - 'http://localhost:8080'
        - 'http://localhost:9001'
      allowed-methods:
        - '*'
      max-age: 3600
  authorization:
    api-gw-header: x-nav-apiKey
    api-gw-key: mock-key
    soknad-til-prosessering-scope: mock-scope
  gateways:
    k9_lookup_url: 'http://localhost:8081'
    k9_dokument_url: 'http://localhost:8132'
    omsorgspengersoknad_mottak_url: 'http://localhost:8083'

http:
  proxyHost: localhost
  proxyPort: 8080
  nonProxyHosts: localhost|127\.0\.0\.1|login\.microsoftonline\.com
https:
  proxyHost: localhost
  proxyPort: 8080

storage:
  redis_mocked: true
  passphrase: "verySecret"