spring:
  profiles:
    active: prod

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/8b7dfc8b-b52e-4741-bde4-d83ea366f94f/v2.0/
          jwk-set-uri: https://login.microsoftonline.com/navnob2c.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1a_idporten
  redis:
    host: ${REDIS_HOST}
    port: 6379

nav.no:
  security:
    cors:
      apply-to-path-pattern: '/**'
      allowed-origins:
        - 'https://omsorgspengesoknad.nav.no'
        - 'https://omsorgspengesoknad-api.nav.no'
        - 'https://omsorgspengesoknad.nais.oera.no'
      allowed-methods:
        - '*'
      max-age: 3600


storage:
  redis_mocked: false
  passphrase: ${STORAGE_PASSPHRASE}