nav.no:
  security:
    scopes:
      omsorgspengesoknad-mottak-scopes: 8a37534e-7387-43af-8123-cb5facd5dc44/.default
    login-service-client-id: 0090b6e1-ffcc-4c37-bc21-049f7d1f0fe5
    cors:
      apply-to-path-pattern: '/**'
      allowed-origins:
        - 'http://localhost:8080'
        - 'http://localhost:9001'
      allowed-methods:
        - '*'
      max-age: 3600
    client:
      azure:
        token-endpoint: "https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/oauth2/v2.0/token"

  authorization:
    api-gw-header: x-nav-apiKey
    api-gw-key: mock-key
    soknad-til-prosessering-scope: mock-scope
  gateways:
    k9_lookup_url: 'http://localhost:8081'
    k9_dokument_url: 'http://localhost:8132'
    omsorgspengersoknad_mottak_url: 'http://localhost:8142'

http:
  proxyHost: localhost
  proxyPort: 8080
  nonProxyHosts: localhost|127\.0\.0\.1|login\.microsoftonline\.com
https:
  proxyHost: localhost
  proxyPort: 8080

storage:
  redis_mocked: true
  passphrase: "verySecret"