spring:
  profiles:
    active: prod

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/8b7dfc8b-b52e-4741-bde4-d83ea366f94f/v2.0/
          jwk-set-uri: https://login.microsoftonline.com/navnob2c.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1a_idporten

nav.no.security:
    login-service-client-id: 45104d6a-f5bc-4e8c-b352-4bbfc9381f25