spring:
  profiles:
    active: dev
  sleuth:
    propagation:
      tag:
        enabled: true
    log:
      slf4j:
        whitelisted-mdc-keys:
    local-keys: x_correlation_id
      - x_correlation_id
    propagation-keys:
      - x_correlation_id
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/d38f25aa-eab8-4c50-9f28-ebf92c1256f2/v2.0/
          jwk-set-uri: https://login.microsoftonline.com/navtestb2c.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1a_idporten_ver1
  servlet:
    multipart:
      enabled: true
      max-file-size: 8MB
      max-request-size: 24MB # Maximum of 24MB, each file max 8 MB
  codec:
    max-in-memory-size: 24000000 # 24 MB

nav.no:
  authorization:
    api-gw-header: x-nav-apiKey
    api-gw-key: ${API_GATEWAY_API_KEY}
  gateways:
    k9_lookup_url: ${K9_OPPSLAG_REGISTER_URL}
    k9_dokument_url: ${K9_DOKUMENT_BASE_URL}
    omsorgspengersoknad_mottak_url: ${OMSORGSPENGERSOKNAD_MOTTAK_BASE_URL}
  cors-addresses:
  security:
    scopes:
      omsorgspengesoknad-mottak-scopes: ${SENDE_SOKNAD_TIL_MOTTAK_SCOPES}
    login-service-client-id: ${LOGIN_SERVICE_CLIENT_ID}
    cors:
      apply-to-path-pattern: '/**'
      allowed-origins:
        - 'http://localhost:8080'
        - 'http://localhost:9001'
      allowed-methods:
        - '*'
      max-age: 3600
    client:
      azure:
        client-id: ${AZURE_CLIENT_ID}
        client-secret: ${AZURE_CLIENT_SECRET}
        token-endpoint: ${AZURE_V2_TOKEN_ENDPOINT}

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  metrics:
    export:
      prometheus:
        enabled: true

storage:
  redis_mocked: true
  passphrase: "verySecret"
http:
  proxyHost:
  proxyPort:
  nonProxyHosts:
https:
  proxyHost:
  proxyPort: