apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: omsorgspenger-api
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{ image }}:{{ tag }}
  port: 8080
  liveness:
    path: /actuator/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /actuator/health
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - https://omsorgspenger-api-q.nav.no
    - https://omsorgspenger-api.nais.oera-q.local
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /actuator/prometheus
  vault:
    enabled: true
  webproxy: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: q
    - name: CORS_ADDRESSES
      value: https://omsorgspengesoknad-q.nav.no, https://omsorgspengesoknad.nais.oera-q.local
    - name: ISSUER
      value: https://login.microsoftonline.com/d38f25aa-eab8-4c50-9f28-ebf92c1256f2/v2.0/
    - name: COOKIE_NAME
      value: selvbetjening-idtoken
    - name: JWKS_URI
      value: https://login.microsoftonline.com/navtestb2c.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1a_idporten_ver1
    - name: K9_OPPSLAG_REGISTER_URL
      value: https://api-gw-q1.adeo.no/helse-reverse-proxy/k9-selvbetjening-oppslag
    - name: K9_DOKUMENT_BASE_URL
      value: https://k9-dokument.nais.oera-q.local
    - name: LOGIN_SERVICE_CLIENT_ID
      value: 0090b6e1-ffcc-4c37-bc21-049f7d1f0fe5